export const Routes = {
  START_UP: 'START_UP',
  MAIN: 'MAIN',
  WELCOME: 'WELCOME',
  HOME: 'HOME',
  PLANET_TWO: 'PLANET_TWO',
  PLANET_THREE: 'PLANET_THREE',
  PLANET_FOUR: 'PLANET_FOUR',
  RESULT: 'RESULT',
};
